name: calling secrets inherit
on:
  workflow_dispatch:
  
jobs:
  # calling the remote & public workflow in a different org in the same business
  calling_remote_public_different_org_same_business_without_inherit:
    uses: korea-dinos/yujincat-test2/.github/workflows/called-inherit.yml@main
    secrets: 
      mapping_test: "test"

  calling_remote_public_different_org_same_business:
    uses: korea-dinos/yujincat-test2/.github/workflows/called-inherit.yml@main
    secrets: inherit
