# This is a basic workflow to help you get started with Actions

name: Calling

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    uses: korea-dinos/yujincat-action/.github/workflows/hello.yml@main
    secrets: inherit
#     uses: korea-dinos/internal-test-yujincat/.github/workflows/hello.yml@main
