name: hello
on: 
  workflow_call:
  workflow_dispatch:
jobs: 
  job1: 
    runs-on: ubuntu-latest
    environment:
      name: z
      url: https://github.com
    steps:
      - name: test env
        run: |
          echo hello secrets.ENV_SECRET : ${{secrets.ENV_SECRET}}
