name: hello
on: 
  workflow_call:
    secrets: 
      ORG_SECRET:
        required: true
  workflow_dispatch:
jobs: 
  job1: 
    runs-on: yujincat
    environment:
      name: z
      url: https://github.com
    steps:
      - name: test env
        run: |
          echo hello secrets.ENV_SECRET : ${{secrets.ENV_SECRET}}
          echo hello secrets.ORG_SECRET : ${{secrets.ORG_SECRET}}

