# This is a basic workflow to help you get started with Actions

name: public
# Controls when the workflow will run
on: 
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    concurrency: one-mickey

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sleep 10
          echo test, and deploy your project.
